<a href="https://colab.research.google.com/github/benedictamobi-madu-cloud/Git-GitHub/blob/main/Pandas_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# My First Data Science Project
Data Manipulation in Pandas  
Date: February 2026

In [1]:
# Import necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Pandas_Data_Manipulation_car_prices.csv to Pandas_Data_Manipulation_car_prices.csv

In [3]:
df = pd.read_csv("Pandas_Data_Manipulation_car_prices.csv")

In [4]:
# view the first 5 Rows

df.head ()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [5]:
# Preview the last few rows of the dataset

df.tail ()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
558832,2015,Kia,K900,Luxury,Sedan,NaN,knalw4d4xf6019304,in,45.0,18255.0,silver,black,avis corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558833,2012,Ram,2500,Power Wagon,Crew Cab,automatic,3c6td5et6cg112407,wa,5.0,54393.0,white,black,i -5 uhlmann rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,automatic,5uxzw0c58cl668465,ca,48.0,50561.0,black,black,financial services remarketing (lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,Nissan,Altima,2.5 S,sedan,automatic,1n4al3ap0fc216050,ga,38.0,16658.0,white,black,enterprise vehicle exchange / tra / rental / t...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,Ford,F-150,XLT,SuperCrew,automatic,1ftfw1et2eke87277,ca,34.0,15008.0,gray,gray,ford motor credit company llc pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

# Understanding the Data

  # A. Random Sampling

In [6]:
# View 5 random rows

df.sample (5)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
168172,2010,Kia,Forte,EX,Sedan,automatic,knafu4a20a5212081,fl,47.0,62960.0,white,gray,tdaf remarketing,6400.0,8600.0,Tue Feb 10 2015 01:00:00 GMT-0800 (PST)
321352,2003,Pontiac,Sunfire,Base,Coupe,automatic,1g2jb12f637198718,ma,34.0,120200.0,yellow,black,imperial chrysler dodge jeep corp,1300.0,1100.0,Tue Feb 17 2015 02:00:00 GMT-0800 (PST)
538225,2012,Nissan,Versa,1.6 S,sedan,automatic,3n1cn7ap0cl883465,tn,33.0,41409.0,gray,black,exeter finance corp,7625.0,7100.0,Wed Jun 17 2015 03:30:00 GMT-0700 (PDT)
43929,2010,BMW,5 Series,528i,Sedan,automatic,wbanu5c53ac128003,fl,25.0,72551.0,white,tan,tdaf remarketing,14600.0,16200.0,Tue Jan 20 2015 01:00:00 GMT-0800 (PST)
409077,2004,Dodge,Durango,Limited,SUV,automatic,1d4hb58n34f137627,mi,21.0,138922.0,red,gray,go financial,2925.0,2100.0,Thu Apr 23 2015 02:30:00 GMT-0700 (PDT)

In [7]:
# B. A quick summary of the DataFrame

df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [8]:
# C. Dataset Dimensions

  # Get shape (rows, columns)

df.shape

(558837, 16)

In [9]:
  # Get number of rows

len(df)

558837

In [10]:
  # Get number of columns

len(df.columns)

16

In [11]:
# D. Viewing Column Names

df.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [12]:
df.columns.tolist()

['year',
 'make',
 'model',
 'trim',
 'body',
 'transmission',
 'vin',
 'state',
 'condition',
 'odometer',
 'color',
 'interior',
 'seller',
 'mmr',
 'sellingprice',
 'saledate']

In [13]:
# Checking Unique Values

  # Number of unique values in each column

print(df.nunique())

year                34
make                96
model              973
trim              1963
body                87
transmission         4
vin             550297
state               64
condition           41
odometer        172278
color               46
interior            17
seller           14263
mmr               1101
sellingprice      1887
saledate          3766
dtype: int64

In [14]:
  # Calculate the number of distinct (unique) values in the "make" column

df["make"].nunique()

96

In [15]:
  #   Calculate the number of distinct (unique) values in the "odometer" column

df["odometer"].nunique()

172278

In [16]:
  #   Calculate the number of distinct (unique) values in the "model" column

df["model"].nunique()

973

In [17]:
# Viewing Specific Column Values

  # Determine which values appear most often in a particular column

print(df["make"].value_counts().head(10))

make
Ford         93554
Chevrolet    60197
Nissan       53946
Toyota       39871
Dodge        30710
Honda        27206
Hyundai      21816
BMW          20719
Kia          18077
Chrysler     17276
Name: count, dtype: int64

In [18]:
print(df["model"].value_counts().head(10))

model
Altima           19349
F-150            14479
Fusion           12946
Camry            12545
Escape           11861
Focus            10394
Accord            9127
3 Series          8204
Grand Caravan     7941
Impala            7923
Name: count, dtype: int64

In [19]:
print(df["odometer"].value_counts().head(10))

odometer
1.0         1318
999999.0      72
10.0          29
21587.0       21
8.0           18
2.0           18
29137.0       18
21310.0       18
23033.0       17
27023.0       17
Name: count, dtype: int64

In [20]:
print(df["transmission"].value_counts())

transmission
automatic    475915
manual        17544
sedan            15
Sedan            11
Name: count, dtype: int64

In [21]:
print(df["color"].value_counts().head(10))

color
black     110970
white     106673
silver     83389
gray       82857
blue       51139
red        43569
—          24685
green      11382
gold       11342
beige       9222
Name: count, dtype: int64

In [22]:
# Summary Statistics

  # df.describe() = a quick statistical summary tool that gives important metrics for only the numeric columns in the dataset (unless otherwise specified )

df.describe()

,year,condition,odometer,mmr,sellingprice
count,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000
mean,2010.038927,30.672365,68320.017767,13769.377495,13611.358810
std,3.966864,13.402832,53398.542821,9679.967174,9749.501628
min,1982.000000,1.000000,1.000000,25.000000,1.000000
25%,2007.000000,23.000000,28371.000000,7100.000000,6900.000000
50%,2012.000000,35.000000,52254.000000,12250.000000,12100.000000
75%,2013.000000,42.000000,99109.000000,18300.000000,18200.000000
max,2015.000000,49.000000,999999.000000,182000.000000,230000.000000

In [23]:
# Summary Statistics for Categorical Columns (object type)

  # df.describe(include='object') provides summary information for all non-numeric columns, like brand names, locations, colors, etc.

df.describe(include='object')

,make,model,trim,body,transmission,vin,state,color,interior,seller,saledate
count,548536,548438,548186,545642,493485,558833,558837,558088,558088,558837,558825
unique,96,973,1963,87,4,550297,64,46,17,14263,3766
top,Ford,Altima,Base,Sedan,automatic,automatic,fl,black,black,nissan-infiniti lt,Tue Feb 10 2015 01:30:00 GMT-0800 (PST)
freq,93554,19349,55817,199437,475915,22,82945,110970,244329,19693,5334

# Filtering Data in Pandas

  # Filtering enables the selection of only the rows that meet certain conditions. It helps when working with a specific part of the dataset.

In [24]:
# A. Filtering Numeric Columns

  # A1. Greater Than (>)

    # Cars priced above $50,000
expensive_cars = df[df['sellingprice'] > 50000]

In [25]:
  # A2. Less Than (<)

    # Cars priced under $5,000
cheap_cars = df[df['sellingprice'] < 5000]

In [26]:
  # A3. Equal To (==)

    # Cars from exactly 2015
cars_2015 = df[df['year'] == 2015]

In [27]:
# B. Filtering Text (Categorical) Columns

  # Exact Match

    # B1. All Toyota cars
toyotas = df[df['make'] == 'toyota']

In [28]:
    # B2. Cars sold in California
california_cars = df[df['state'] == 'ca']

In [29]:
# C. Filtering under Multiple Conditions
# Often one needs to filter by more than one condition

  # C1. AND Condition (&) {that is, both conditions must be true.}

    # Toyota cars priced under $15,000
cheap_toyotas = df[(df['make'] == 'toyota') & (df['sellingprice'] < 15000)]

In [30]:
  # C2. OR Condition (|) {At least one condition must be true}

    # Cars that are either Toyota OR Honda
toyota_or_honda = df[(df['make'] == 'toyota') | (df['make'] == 'honda')]

# This selects all rows where the make column is either "toyota" or "honda".

# Data Cleaning

# Before analyzing or working with a dataset, there is need to find and fix problems in the data.

# Common issues in real-world data include: missing values — cells that are empty or recorded as NaN (Not a Number), Duplicates — repeated rows, and Inconsistencies — typos, wrong formats, or mixed data types.

  # Pandas provides powerful tools to handle these issues so data is ready for analysis.

In [31]:
# 1. df.isna() returns a DataFrame of True and False values, where:
  # 1a. True means the value is missing
  # 1b. False means the value is present

df.isna()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558832,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
558833,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
558834,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
558835,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
558836,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [32]:
# df.isna().sum() adds up the number of True values (the number of missing values) in each column.
# That is, it is used to check how many missing values exist in each column.

df.isna().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [33]:
# Understanding .isna() vs .isnull()

  # Both functions do the same thing — they identify missing values in a DataFrame or Series.
  # Both return the count of missing values.
  # They are interchangeably used in pandas.

df.isnull().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

**Dropping Null Values in a Dataset (dropna())**

Real-world datasets commonly have missing values, empty cells or entries, marked as **NaN (Not a Number).** These can occur due to:

*   Incomplete data collection


*   Data entry errors
*   Data corruption



*   Not applicable fields





**Dropping nulls is one way to clean your dataset, especially when:**



*   The number of missing values is small
*   The missing rows are not critical to your analysis


*   You want to ensure smooth modeling or analysis (most ML algorithms don't handle nulls well)







**Caution**: Dropping rows with nulls can lead to data loss and potential bias if the missing data follows a pattern. Consider alternatives like imputation (filling missing values) or using algorithms that handle missing data natively.

In [34]:
# Calculating the percentage of missing values

  # /len(df) Divides the null count by the total number of rows to get a proportion

missing_percentage = (df.isnull().sum() / len(df)) * 100
print (missing_percentage)

year             0.000000
make             1.843292
model            1.860829
trim             1.905922
body             2.361154
transmission    11.694287
vin              0.000716
state            0.000000
condition        2.115107
odometer         0.016821
color            0.134028
interior         0.134028
seller           0.000000
mmr              0.006800
sellingprice     0.002147
saledate         0.002147
dtype: float64

In [35]:
# Drop all rows that have at least one missing value

# df_clean = df.dropna() Removes every row that has at least one null value. The result is stored in a new DataFrame df_clean.

df_clean = df.dropna()

In [36]:
print("Before:", df.shape)
print("After :", df_clean.shape)

Before: (558837, 16)
After : (472325, 16)

**Dropping Columns That Contain Any Missing Values**



Sometimes a column may contain missing values in places where they cannot be meaningfully filled. In such cases, one may decide to remove the entire column.

In [38]:
df_dropped_cols = df.dropna(axis=1)

**Explanation:**



*   axis=1 tells pandas to drop columns instead of rows.
*   A column will be removed if at least one missing value is found in it.


*   This is a strict approach, so use it only when the column isn’t important or when missing values are too frequent to fix.

In [39]:
print("before:", df.shape)
print("after :", df_dropped_cols.shape)

before: (558837, 16)
after : (558837, 3)

In [40]:
df = df.dropna(subset=['model'])

**Selecting Specific Columns**

In [41]:
# A. Single Column

df['model']

0                     Sorento
1                     Sorento
2                    3 Series
3                         S60
4         6 Series Gran Coupe
                 ...
558832                   K900
558833                   2500
558834                     X5
558835                 Altima
558836                  F-150
Name: model, Length: 548438, dtype: object

In [42]:
# B. Multiple Columns

df[['make', 'model', 'sellingprice']]

          make                model  sellingprice
0          Kia              Sorento       21500.0
1          Kia              Sorento       21500.0
2          BMW             3 Series       30000.0
3        Volvo                  S60       27750.0
4          BMW  6 Series Gran Coupe       67000.0
...        ...                  ...           ...
558832     Kia                 K900       33000.0
558833     Ram                 2500       30800.0
558834     BMW                   X5       34000.0
558835  Nissan               Altima       11100.0
558836    Ford                F-150       26700.0

[548438 rows x 3 columns]

# **Renaming Columns in Pandas**

Renaming columns is a common task when working with datasets. Reasons may include to:

* Make names more readable or descriptive
* Clean up messy or inconsistent names
* Standardize naming conventions (lowercase, no spaces)
* Match column names with another dataset for merging
* Make names Python-friendly (no spaces or special characters)

#  **Renaming Specific Columns**

**Using rename() Method**

The most flexible way to rename columns. Pass a dictionary mapping old names to new names.

**Syntax:**

df.rename(columns={'old_name': 'new_name'}, inplace=True)
# OR
df = df.rename(columns={'old_name': 'new_name'})

**A. Single Column:**

In [43]:
# Rename 'sellingprice' to 'selling_price'

df = df.rename(columns={'sellingprice': 'selling_price'})

print(df.columns.tolist())

['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state', 'condition', 'odometer', 'color', 'interior', 'seller', 'mmr', 'selling_price', 'saledate']

**B. Multiple Columns:**

In [44]:
# Rename multiple columns at once

df = df.rename(columns={
    'sellingprice': 'selling_price',
    'mmr': 'market_value',
    'vin': 'vehicle_id',
    'saledate': 'sale_date'
})

print(df.columns.tolist())

['year', 'make', 'model', 'trim', 'body', 'transmission', 'vehicle_id', 'state', 'condition', 'odometer', 'color', 'interior', 'seller', 'market_value', 'selling_price', 'sale_date']

## **C. Using inplace=True:**

***inplace=True*** modifies the original DataFrame. Without it, one must assign the result back to df.

In [45]:
# Modify the original DataFrame directly

df.rename(columns={'odometer': 'mileage'}, inplace=True)



***It tells pandas:***

    Change the column name from 'odometer' to 'mileage'.

inplace=True

***This means:***

    Apply the change directly to df instead of returning a new DataFrame.

# **GroupBy and Aggregations in Pandas**

The GroupBy operation in Pandas is used to analyze data by categories and compute summary statistics for each group. This is essential when one wants to understand patterns or compare groups within his/her dataset.

**With groupby(), one can answer practical questions such as:**

* Which car brand has the highest average selling price?

* How many cars were sold in each state?

* What is the average condition rating for each seller?


**How GroupBy Works**

One splits one's DataFrame into groups based on the values in one or more columns, and then apply an aggregation function.

Common aggregation functions include:

* .mean() — average

* .sum() — total

* .count() — number of rows

* .min() — smallest value

* .max() — largest value

* .median() — middle value

One can group by single column or multiple columns, and then chain the result with sorting, filtering, or plotting.

      A. Average selling price per car brand

In [50]:
df.groupby('make')['selling_price'].mean()

make
Acura           14017.268260
Aston Martin    54812.000000
Audi            19901.310398
BMW             21234.340038
Bentley         74367.672414
                    ...
subaru           3710.416667
suzuki           4810.000000
toyota           7339.105263
volkswagen       6145.833333
vw              13672.916667
Name: selling_price, Length: 96, dtype: float64

This gives a simple, clean summary of average price per brand — way easier to interpret than scanning all 500,000+ rows.

    B. Number of cars sold in each state

In [51]:
df.groupby('state')['selling_price'].count().sort_values(ascending=False).head(10)

state
fl    81480
ca    71658
pa    53154
tx    45195
ga    34056
nj    27331
il    23188
nc    21333
oh    21209
tn    20691
Name: selling_price, dtype: int64

This shows the top-selling states by average price

     C. Grouping by Multiple Columns

In [52]:
df.groupby(['make', 'state'])['selling_price'].mean()

make   state
Acura  ab        2300.000000
       az       11437.790698
       ca       14106.790865
       co       15024.137931
       fl       11680.376344
                    ...
vw     mn        1500.000000
       oh       21850.000000
       on        7606.250000
       va         500.000000
       wa        2500.000000
Name: selling_price, Length: 2061, dtype: float64

# **Data Visualization with Matplotlib**

Data Visualization is the process of turning raw data into visual formats like charts, graphs, plots, and maps.

* It helps you see patterns, trends, and insights quickly.

* Our brains understand pictures faster than tables.

* A well-designed chart can tell a story at a glance that might take pages of numbers to explain.

 **Common Visualization Types:**

| Chart Type         | When to Use                      | Code Example                    |
| ------------------ | -------------------------------- | ------------------------------- |
| **Line**           | Trends over time                 | `plt.plot(x, y)`                |
| **Bar**            | Compare categories               | `plt.bar(x, y)`                 |
| **Horizontal Bar** | Long category names              | `plt.barh(x, y)`                |
| **Histogram**      | Data distribution                | `plt.hist(data)`                |
| **Pie**            | Parts of a whole                 | `plt.pie(values, labels=names)` |
| **Scatter**        | Relationship between 2 variables | `plt.scatter(x, y)`             |
| **Box Plot**       | Distribution & outliers          | `plt.boxplot(data)`             |