<a href="https://colab.research.google.com/github/benedictamobi-madu-cloud/Git-GitHub/blob/main/Pandas_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# My First Data Science Project
Data Manipulation in Pandas  
Date: February 2026

In [1]:
# Import necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Pandas_Data_Manipulation_car_prices.csv to Pandas_Data_Manipulation_car_prices.csv

In [3]:
df = pd.read_csv("Pandas_Data_Manipulation_car_prices.csv")

In [4]:
# view the first 5 Rows

df.head ()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [5]:
# Preview the last few rows of the dataset

df.tail ()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
558832,2015,Kia,K900,Luxury,Sedan,NaN,knalw4d4xf6019304,in,45.0,18255.0,silver,black,avis corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558833,2012,Ram,2500,Power Wagon,Crew Cab,automatic,3c6td5et6cg112407,wa,5.0,54393.0,white,black,i -5 uhlmann rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,automatic,5uxzw0c58cl668465,ca,48.0,50561.0,black,black,financial services remarketing (lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,Nissan,Altima,2.5 S,sedan,automatic,1n4al3ap0fc216050,ga,38.0,16658.0,white,black,enterprise vehicle exchange / tra / rental / t...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,Ford,F-150,XLT,SuperCrew,automatic,1ftfw1et2eke87277,ca,34.0,15008.0,gray,gray,ford motor credit company llc pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

# Understanding the Data

  # A. Random Sampling

In [6]:
# View 5 random rows

df.sample (5)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
143183,2007,Infiniti,G35,Base,Coupe,automatic,jnkcv54e77m900557,oh,44.0,64282.0,red,black,lexus rivercenter,11450.0,12400.0,Thu Jan 15 2015 02:00:00 GMT-0800 (PST)
528599,2007,Mercedes-Benz,GL-Class,GL450,suv,NaN,4jgbf71e27a159208,pa,33.0,87834.0,black,black,r hollenshead auto sales inc,15350.0,14750.0,Fri Jun 12 2015 02:00:00 GMT-0700 (PDT)
541426,2006,Nissan,Murano,S,suv,NaN,jn8az08t26w400385,ca,39.0,85593.0,white,beige,rover of orange,6675.0,7700.0,Wed Jun 17 2015 05:30:00 GMT-0700 (PDT)
540253,2008,Chrysler,Town and Country,Touring,minivan,automatic,2a8hr54p28r634997,mo,21.0,125684.0,silver,gray,performance chrysler dodge jeep ram of bellevue,5650.0,7200.0,Wed Jun 17 2015 03:30:00 GMT-0700 (PDT)
411333,2014,Ram,1500,Tradesman,Crew Cab,automatic,1c6rr7kt4es480303,il,2.0,6726.0,black,gray,ally,28300.0,26750.0,Thu May 21 2015 03:00:00 GMT-0700 (PDT)

In [7]:
# B. A quick summary of the DataFrame

df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [9]:
# C. Dataset Dimensions

  # Get shape (rows, columns)

df.shape

(558837, 16)

In [10]:
  # Get number of rows

len(df)

558837

In [11]:
  # Get number of columns

len(df.columns)

16

In [12]:
# D. Viewing Column Names

df.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [13]:
df.columns.tolist()

['year',
 'make',
 'model',
 'trim',
 'body',
 'transmission',
 'vin',
 'state',
 'condition',
 'odometer',
 'color',
 'interior',
 'seller',
 'mmr',
 'sellingprice',
 'saledate']

In [15]:
# Checking Unique Values

  # Number of unique values in each column

print(df.nunique())

year                34
make                96
model              973
trim              1963
body                87
transmission         4
vin             550297
state               64
condition           41
odometer        172278
color               46
interior            17
seller           14263
mmr               1101
sellingprice      1887
saledate          3766
dtype: int64

In [17]:
  # Calculate the number of distinct (unique) values in the "make" column

df["make"].nunique()

96

In [18]:
  #   Calculate the number of distinct (unique) values in the "odometer" column

df["odometer"].nunique()

172278

In [19]:
  #   Calculate the number of distinct (unique) values in the "model" column

df["model"].nunique()

973

In [20]:
# Viewing Specific Column Values

  # Determine which values appear most often in a particular column

print(df["make"].value_counts().head(10))

make
Ford         93554
Chevrolet    60197
Nissan       53946
Toyota       39871
Dodge        30710
Honda        27206
Hyundai      21816
BMW          20719
Kia          18077
Chrysler     17276
Name: count, dtype: int64

In [22]:
print(df["model"].value_counts().head(10))

model
Altima           19349
F-150            14479
Fusion           12946
Camry            12545
Escape           11861
Focus            10394
Accord            9127
3 Series          8204
Grand Caravan     7941
Impala            7923
Name: count, dtype: int64

In [23]:
print(df["odometer"].value_counts().head(10))

odometer
1.0         1318
999999.0      72
10.0          29
21587.0       21
8.0           18
2.0           18
29137.0       18
21310.0       18
23033.0       17
27023.0       17
Name: count, dtype: int64

In [24]:
print(df["transmission"].value_counts())

transmission
automatic    475915
manual        17544
sedan            15
Sedan            11
Name: count, dtype: int64

In [25]:
print(df["color"].value_counts().head(10))

color
black     110970
white     106673
silver     83389
gray       82857
blue       51139
red        43569
—          24685
green      11382
gold       11342
beige       9222
Name: count, dtype: int64

In [26]:
# Summary Statistics

  # df.describe() = a quick statistical summary tool that gives important metrics for only the numeric columns in the dataset (unless otherwise specified )

df.describe()

,year,condition,odometer,mmr,sellingprice
count,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000
mean,2010.038927,30.672365,68320.017767,13769.377495,13611.358810
std,3.966864,13.402832,53398.542821,9679.967174,9749.501628
min,1982.000000,1.000000,1.000000,25.000000,1.000000
25%,2007.000000,23.000000,28371.000000,7100.000000,6900.000000
50%,2012.000000,35.000000,52254.000000,12250.000000,12100.000000
75%,2013.000000,42.000000,99109.000000,18300.000000,18200.000000
max,2015.000000,49.000000,999999.000000,182000.000000,230000.000000

In [28]:
# Summary Statistics for Categorical Columns (object type)

  # df.describe(include='object') provides summary information for all non-numeric columns, like brand names, locations, colors, etc.

df.describe(include='object')

,make,model,trim,body,transmission,vin,state,color,interior,seller,saledate
count,548536,548438,548186,545642,493485,558833,558837,558088,558088,558837,558825
unique,96,973,1963,87,4,550297,64,46,17,14263,3766
top,Ford,Altima,Base,Sedan,automatic,automatic,fl,black,black,nissan-infiniti lt,Tue Feb 10 2015 01:30:00 GMT-0800 (PST)
freq,93554,19349,55817,199437,475915,22,82945,110970,244329,19693,5334

# Filtering Data in Pandas

  # Filtering enables the selection of only the rows that meet certain conditions. It helps when working with a specific part of the dataset.

In [29]:
# A. Filtering Numeric Columns

  # A1. Greater Than (>)

    # Cars priced above $50,000
expensive_cars = df[df['sellingprice'] > 50000]

In [30]:
  # A2. Less Than (<)

    # Cars priced under $5,000
cheap_cars = df[df['sellingprice'] < 5000]

In [31]:
  # A3. Equal To (==)

    # Cars from exactly 2015
cars_2015 = df[df['year'] == 2015]

In [32]:
# B. Filtering Text (Categorical) Columns

  # Exact Match

    # B1. All Toyota cars
toyotas = df[df['make'] == 'toyota']

In [33]:
    # B2. Cars sold in California
california_cars = df[df['state'] == 'ca']

In [34]:
# C. Filtering under Multiple Conditions
# Often one needs to filter by more than one condition

  # C1. AND Condition (&) {that is, both conditions must be true.}

    # Toyota cars priced under $15,000
cheap_toyotas = df[(df['make'] == 'toyota') & (df['sellingprice'] < 15000)]

In [35]:
  # C2. OR Condition (|) {At least one condition must be true}

    # Cars that are either Toyota OR Honda
toyota_or_honda = df[(df['make'] == 'toyota') | (df['make'] == 'honda')]

# This selects all rows where the make column is either "toyota" or "honda".

# Data Cleaning

# Before analyzing or working with a dataset, there is need to find and fix problems in the data.

# Common issues in real-world data include: missing values — cells that are empty or recorded as NaN (Not a Number), Duplicates — repeated rows, and Inconsistencies — typos, wrong formats, or mixed data types.